name: flutter_ocr
description: "Document Scanner App"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.2.1
  camera: ^0.11.3
  image_editor_plus: ^1.0.8
  flutter_animate: ^4.5.2
  image: ^4.5.4
  google_mlkit_entity_extraction: ^0.15.1
  crop_your_image: ^2.0.0
  image_gallery_saver_plus: ^4.0.1
  provider: ^6.1.1
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  flutter_tts: ^4.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/f1.png
